apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid2
spec:
  replicas: 4  # El HPA ajustará este valor automáticamente
  selector:
    matchLabels:
      app: hybrid2
  template:
    metadata:
      labels:
        app: hybrid2
    spec:
      containers:
      - name: hybrid2
        image: mdragonetti/gsa
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
      imagePullSecrets:
      - name: regcred
