apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid2
spec:
  replicas: 1  # El HPA ajustará este valor automáticamente
  selector:
    matchLabels:
      app: hybrid2
  template:
    metadata:
      labels:
        app: hybrid2
    spec:
      containers:
      - name: hybrid2
        image: mdragonetti/gsa
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
      imagePullSecrets:
      - name: regcred

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hybrid2-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hybrid2
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Escala hacia arriba si la CPU supera el 100%
