apiVersion: v1
kind: Service
metadata:
  name: hybrid2-service
  labels:
    app: hybrid2
spec:
  type: NodePort  # Change from LoadBalancer to NodePort
  ports:
    - port: 8082    # Port that the service will expose internally
      targetPort: 8082
      nodePort: 32556  # Optional: specify a fixed NodePort
  selector:
    app: hybrid2

